apiVersion: v1
kind: Service
metadata:
  name: openshift-mcp-server
  namespace: openshift-mcp-server
  labels:
    app: openshift-mcp-server
spec:
  selector:
    app: openshift-mcp-server
  ports:
    - name: http
      port: 80
      targetPort: http
